# Basic imports

In [7]:
import sys
sys.path.append("..")
import trackhhl.toy.simple_generator as toy
import trackhhl.hamiltonians.simple_hamiltonian as hamiltonian
import numpy as np

# Detector

We are going to define a simple detector geometry of 3 parallel infinitely large modules, placed along the $z$-axis

In [8]:
N_MODULES = 3
LX = float("+inf")
LY = float("+inf")
Z_SPACING = 1.0

detector = toy.SimpleDetectorGeometry(
    module_id=list(range(N_MODULES)),
    lx=[LX]*N_MODULES,
    ly=[LY]*N_MODULES,
    z=[i+Z_SPACING for i in range(N_MODULES)]
)

detector

SimpleDetectorGeometry(module_id=[0, 1, 2], lx=[inf, inf, inf], ly=[inf, inf, inf], z=[1.0, 2.0, 3.0])

# Particle generator

Now we define a simple particle generator that will fire particles flying in straight lines through the our detector.

In [9]:
generator = toy.SimpleGenerator(
    detector_geometry=detector,
    theta_max=np.pi/6
)

Let's generate a simple event

In [10]:
N_PARTICLES = 3
event = generator.generate_event(N_PARTICLES)
event.hits

[Hit(hit_id=0, x=np.float64(0.4777329763105493), y=np.float64(0.16071254174072944), z=1.0, module_id=0, track_id=0),
 Hit(hit_id=3, x=np.float64(0.1772356363218551), y=np.float64(0.10869757743312537), z=1.0, module_id=0, track_id=1),
 Hit(hit_id=6, x=np.float64(0.47516643304038203), y=np.float64(-0.15505234704757345), z=1.0, module_id=0, track_id=2),
 Hit(hit_id=1, x=np.float64(0.9554659526210986), y=np.float64(0.3214250834814589), z=2.0, module_id=1, track_id=0),
 Hit(hit_id=4, x=np.float64(0.3544712726437102), y=np.float64(0.21739515486625074), z=2.0, module_id=1, track_id=1),
 Hit(hit_id=7, x=np.float64(0.9503328660807641), y=np.float64(-0.3101046940951469), z=2.0, module_id=1, track_id=2),
 Hit(hit_id=2, x=np.float64(1.433198928931648), y=np.float64(0.48213762522218834), z=3.0, module_id=2, track_id=0),
 Hit(hit_id=5, x=np.float64(0.5317069089655653), y=np.float64(0.32609273229937613), z=3.0, module_id=2, track_id=1),
 Hit(hit_id=8, x=np.float64(1.4254992991211461), y=np.float64(-0

# Hamiltonian initialization

Let's initialize the Hamiltonian.

In [11]:
ham = hamiltonian.SimpleHamiltonian(
    epsilon=1e-7,
    gamma=2.0,
    delta=1.0
)

In [12]:
ham.construct_hamiltonian(event=event)

(<18x18 sparse matrix of type '<class 'numpy.float64'>'
 	with 24 stored elements in Compressed Sparse Column format>,
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]))

# Classical solver

Let's solve this event using a classical linear solver (the Conjugate Gradient Descent method)

In [13]:
classical_solution = ham.solve_classicaly()
classical_solution

array([0.5       , 0.33333333, 0.33333333, 0.33333333, 0.5       ,
       0.33333333, 0.33333333, 0.33333333, 0.5       , 0.5       ,
       0.33333333, 0.33333333, 0.33333333, 0.5       , 0.33333333,
       0.33333333, 0.33333333, 0.5       ])

Let's apply a threshold $T = 0.45$

In [14]:
T = .45

In [15]:
discretized_classical_solution = (classical_solution > T).astype(int)
discretized_classical_solution

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1])

# HHL solver

Now let's solve the same event using the HHL linear solver provided by Qiskit.

In [17]:
hhl_solution = ham.solve_hhl()
hhl_solution

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

Let's discretize using the same threshold $T=0.45$

In [ ]:
discretized_hhl_solution = (hhl_solution > .45).astype(int)
discretized_classical_solution

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1])

# Comparison

Let's compare the two solutions with the Monte Carlo truth

In [ ]:
print("Classical solution: \t", discretized_classical_solution)
print("HHL solution: \t\t", discretized_classical_solution)
print()
MC_truth = [ 1 if seg.hit_from.track_id == seg.hit_to.track_id else 0 for seg in ham.segments]
print("MC truth: \t\t",np.array(MC_truth))

Classical solution: 	 [1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1]
HHL solution: 		 [1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1]

MC truth: 		 [1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 1]
